Models/Photo.cs
#pragma warning disable CS8618

namespace music.Models;

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

public class Photo
{

    [Key]
    public int PhotoId { get;set; }

    [Required]
    [MinLength(2)]
    [MaxLength(30)]
    public string Title { get;set; }

    [DisplayName("Image URL")]
    public string? ImgURL { get;set; }

    public DateTime CreatedAt {get;set;} = DateTime.Now;
    public DateTime UpdatedAt {get;set;} = DateTime.Now;

    public int UserId { get;set; }

    public User? ReportingUser { get;set; }
}

Controllers/ComputerController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using music.Models;

namespace music.Controllers;

public class ComputerController : Controller
{
    private MyContext _context;
    private readonly ILogger<ComputerController> _logger;

    public ComputerController(ILogger<ComputerController> logger, MyContext context)
    {
        _logger = logger;
        _context = context;
    }

    [HttpGet("")]
    public ViewResult Ups()
    {
        return View("~/Views/Project/Ups.cshtml");
    }
    [HttpGet]
    public IActionResult LoadingPage()
    {
        return View("~/Views/Project/LoadingPage.cshtml");
    }
    [HttpGet]
    public IActionResult ShuttingDown()
    {
        return View("~/Views/Project/ShuttingDown.cshtml");
    }
}

Views/Project/AddPhoto.cshtml
@{
    ViewData["Title"] = "Add photo";
    Layout = "_Empty";
}
<a asp-action="Photo">
    <div>
        <img style="font: 100px; height: 63px; width: 75px; margin-left: 90.1%; margin-top: 130px; border-radius: 0px"
            src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWZALotUkFOOV13iv-KnhMhC2Amsr49Ruh6yRKEYGoDXOpOibGNdvx0VuKiz68K_W9sUA&usqp=CAU" />
    </div>
</a>

<style>
    body {
        background-image: url('https://cdn.foliovision.com/images/2013/05/Run-Performance-Monitor.jpg');
        background-size: 100% 100%;
        background-repeat: no-repeat;
        background-position: center;
    }
    .cover {
        position: absolute;
        top: 205px;
        left: 150px;
        width: 80%;
        height: 460px;
        background-color:#ece9d8;
    }

    
</style>
<div class="cover">
    @model Photo
    <form asp-action="CreatePhoto" asp-controller="XP" method="Post" class="col-6">
        <h2>Download</h2>
        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control">
            <span class="text-danger" asp-validation-for="Title"></span>
        </div>
        <div class="form-group">
            <label asp-for="ImgURL"></label>
            <input asp-for="ImgURL" class="form-control">
            <span class="text-danger" asp-validation-for="ImgURL"></span>
        </div>
        <button class="btn btn-primary mt-2">Download</button>
    </form>
</div>

Views/Project/CalculatorPage.cshtml
@{
    ViewData["Title"] = "Calculator";
    Layout = "_Empty";
}

@model string

<h1>Calculator</h1>
<div style="background-image: linear-gradient(#ecf4fc,#d9e4f1); width: 260px; border: 1px solid black; padding: 10px; border-radius: 2px; ">
    <input type="text" name="number" value="@Model" style="background-image: linear-gradient(#e5eefb,#feffff);width: 100%; height: 80px; font-size: 20px; padding: 10px; border: none; border-radius: 2px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2); border: 1px solid #8797aa; " />
        <div style="margin-top:10px;">
            <button type="button" name="button" value="MC" onclick="document.getElementsByName('number')[0].value += 'MC'" style="color:#1e395b; margin-right: 5px; margin-bottom:5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-color: #d4e0ed; border: 1px solid #8797aa; cursor: pointer;">MC</button>
            <button type="button" name="button" value="MR" onclick="document.getElementsByName('number')[0].value += 'MR'" style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-color: #d4e0ed; border: 1px solid #8797aa; cursor: pointer;">MR</button>
            <button type="button" name="button" value="MS" onclick="document.getElementsByName('number')[0].value += 'MS'" style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-color: #d4e0ed; border: 1px solid #8797aa; cursor: pointer;">MS</button>
            <button type="button" name="button" value="M+" onclick="document.getElementsByName('number')[0].value += 'M+'" style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-color: #d4e0ed; border: 1px solid #8797aa; cursor: pointer;">M+</button>
            <button type="button" name="button" value="M-" onclick="document.getElementsByName('number')[0].value += 'M-'" style="color:#1e395b; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-color: #d4e0ed; border: 1px solid #8797aa; cursor: pointer;">M-</button>
            <br />
            <button type="button" name="button" value="backspace" onclick="document.getElementsByName('number')[0].value += 'backspace'" style="color:#1e395b; margin-right: 5px; margin-top:5px; margin-bottom:5px;box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#edf3f9,#d5e0ee); border: 1px solid #8797aa; cursor: pointer;"><-</button>
            <button type="button" name="button" value="CE" onclick="document.getElementsByName('number')[0].value += 'CE'" style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#edf3f9,#d5e0ee); border: 1px solid #8797aa; cursor: pointer;">CE</button>
            <button type="button" name="button" value="C" onclick="document.getElementsByName('number')[0].value += 'C'" style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#edf3f9,#d5e0ee); border: 1px solid #8797aa; cursor: pointer;">C</button>
            <button type="button" id="plus-button" name="button" value="+_" onclick="document.getElementsByName('number')[0].value += '+_'" style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#edf3f9,#d5e0ee); border: 1px solid #8797aa; cursor: pointer;">+_</button>
            <button type="button" name="button" value="sqrt" onclick="document.getElementsByName('number')[0].value += 'sqrt'"style="color:#1e395b; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#edf3f9,#d5e0ee); border: 1px solid #8797aa; cursor: pointer;">sqrt</button>
            <br />
            <button type="button" name="button" value="7" onclick="document.getElementsByName('number')[0].value += '7'"style="color:#1e395b; margin-right: 5px; margin-top:5px; margin-bottom:5px;box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#f6fafe,#e7edf5); border: 1px solid #8797aa; cursor: pointer;">7</button>
            <button type="button" name="button" value="8" onclick="document.getElementsByName('number')[0].value += '8'"style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#f6fafe,#e7edf5); border: 1px solid #8797aa; cursor: pointer;">8</button>
            <button type="button" name="button" value="9" onclick="document.getElementsByName('number')[0].value += '9'"style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#f6fafe,#e7edf5); border: 1px solid #8797aa; cursor: pointer;">9</button>
            <button type="button" name="button" value="/" onclick="document.getElementsByName('number')[0].value += '/'"style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#edf3f9,#d5e0ee); border: 1px solid #8797aa; cursor: pointer;">/</button>
            <button type="button" name="button" value="%" onclick="document.getElementsByName('number')[0].value += '%'"style="color:#1e395b; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#edf3f9,#d5e0ee); border: 1px solid #8797aa; cursor: pointer;">%</button>
            <br />
            <button type="button" name="button" value="4" onclick="document.getElementsByName('number')[0].value += '4'"style="color:#1e395b; margin-right: 5px; margin-top:5px; margin-bottom:5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#f6fafe,#e7edf5); border: 1px solid #8797aa; cursor: pointer;">4</button>
            <button type="button" name="button" value="5" onclick="document.getElementsByName('number')[0].value += '5'"style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#f6fafe,#e7edf5); border: 1px solid #8797aa; cursor: pointer;">5</button>
            <button type="button" name="button" value="6" onclick="document.getElementsByName('number')[0].value += '6'"style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#f6fafe,#e7edf5); border: 1px solid #8797aa; cursor: pointer;">6</button>
            <button type="button" name="button" value="*" onclick="document.getElementsByName('number')[0].value += '*'"style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#edf3f9,#d5e0ee); border: 1px solid #8797aa; cursor: pointer;">*</button>
            <button type="button" name="button" value="1/x" onclick="document.getElementsByName('number')[0].value += '1/x'"style="color:#1e395b; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#edf3f9,#d5e0ee); border: 1px solid #8797aa; cursor: pointer;">1/x</button>
            <br />
            <button type="button" name="button" value="1" onclick="document.getElementsByName('number')[0].value += '1'"style="color:#1e395b; margin-right: 5px; margin-top:5px; margin-bottom:5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#f6fafe,#e7edf5); border: 1px solid #8797aa; cursor: pointer;">1</button>
            <button type="button" name="button" value="2" onclick="document.getElementsByName('number')[0].value += '2'"style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#f6fafe,#e7edf5); border: 1px solid #8797aa; cursor: pointer;">2</button>
            <button type="button" name="button" value="3" onclick="document.getElementsByName('number')[0].value += '3'"style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#f6fafe,#e7edf5); border: 1px solid #8797aa; cursor: pointer;">3</button>
            <button type="button" name="button" value="-" onclick="document.getElementsByName('number')[0].value += '-'"style="color:#1e395b; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#edf3f9,#d5e0ee); border: 1px solid #8797aa; cursor: pointer;">-</button>
            <br />
            <button type="button" name="button" value="0" onclick="document.getElementsByName('number')[0].value += '0'"style="color:#1e395b; margin-top:5px; margin-right: 5px; margin-bottom:5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 85px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#f6fafe,#e7edf5); border: 1px solid #8797aa; cursor: pointer;">0</button>
            <button type="button" name="button" value="." onclick="document.getElementsByName('number')[0].value += '.'"style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#f6fafe,#e7edf5); border: 1px solid #8797aa; cursor: pointer;">.</button>
            <button type="button" name="button" value="+" onclick="document.getElementsByName('number')[0].value += '+'"style="color:#1e395b; margin-right: 5px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 40px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#edf3f9,#d5e0ee); border: 1px solid #8797aa; cursor: pointer;">+</button>
            <button type="button" name="button" value="=" onclick="document.getElementsByName('number')[0].value += '='"style="color:#1e395b; box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);width: 40px; height: 85px; font-size: 18px; padding: 10px; border: none; border-radius: 3px; background-image: linear-gradient(#edf3f9,#d5e0ee); border: 1px solid #8797aa; cursor: pointer;">=</button>
        </div>

<p>Result: @Model</p>

Views/Project/LoadingPage.cshtml
@{
    ViewData["Title"] = "loading..";
    Layout = "_Empty";
}

<style>
    body {
        background-image: url('https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/d1ebab8b-2b0b-4d87-a313-481d83d85afa/d9rjn08-f6a328b9-74f2-4fc1-9efe-d8e474713416.gif?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2QxZWJhYjhiLTJiMGItNGQ4Ny1hMzEzLTQ4MWQ4M2Q4NWFmYVwvZDlyam4wOC1mNmEzMjhiOS03NGYyLTRmYzEtOWVmZS1kOGU0NzQ3MTM0MTYuZ2lmIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.whuZe9TB-dUJj-2CKhWHnKjRvm5MTaRPus7pUeIn4Tg');
        background-size: cover;
        background-position: center;
        }
    .click {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 1;
    }
</style>

<a asp-controller="User" asp-action="LogAndReg" class="click"></a>

Views/Project/LogAndReg.cshtml
@{
    ViewData["Title"] = "computer";
    Layout = "_Empty";
}

<style>
    body {
        background-image: url('https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/c0bd4a43-0e20-4bc5-b845-a33b8ad62933/d2tbbbl-591fc5c2-ab6a-460b-8d70-00af74277288.png');
        background-size: 100% 100%;
        background-repeat: no-repeat;
        background-position: center;
    }

    .button {
        margin-top: 0px;
        margin-left: 430px;
        padding-left: 15px;
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
        width: 40px;
        height: 25px;
        font-size: 14px;
        color: white;
        border: none;
        border-radius: 3px;
        border: 1px solid #6e89ab;
    }

    .box {
        border-radius: 10px;
        text-align: center;
        width: 60%;
        margin-left: 550px;
        background-image: linear-gradient(to left, rgba(255,0,0,0), #183ba9);
        padding: 0px;
    }

    .box:first-child {
        margin-top: 100px;
    }

    .logo {
        font-size: 90px;
        margin-top: 50px;
    }

    .text {
        color: white;
    }
</style>

@model List<User>
@foreach (var u in Model)
{
    <div>
        <div class="col-6">
            <a asp-route-UserId="@u.UserId" asp-controller="User" asp-action="Login">
                <div class=box>
                    <p class="logo">@u.Image</p>
                    <p class="text">@u.Name</p>
            <div>
                <form asp-route-userId="@u.UserId" asp-action="DeleteUser" asp-controller="User" method="Post">
                    <button>
                        <img src="https://www.eightforums.com/attachments/recycle_bin_empty-png.40964/" alt="Delete"
                            style="width: 20px; height: 20px;">
                    </button>
                </form>
            </div>
                </div>
            </a>

        </div>
    </div>

}

<a asp-controller="User" asp-action="Register">
    <div class="button">+</div>
</a>

Views/Project/LoggingOff.cshtml
@{
    ViewData["Title"] = "turnoff?";
    Layout = "_Empty";
}

<style>
    body {
        background-image: url('https://thetechgears.com/wp-content/uploads/2014/04/Microsoft-Ends-Support-for-Windows-XP.jpg');
        background-size: 100% 100%;
        background-repeat: no-repeat;
        background-position: center;
    }
</style>

<a asp-action="ShuttingDown" asp-controller="Computer">
    <div style="font: 20px; height: 20px; width: 10px">
        <img style="height: 148px; width: 140px; margin-left: 580px; margin-top: 320px;"
            src="https://64.media.tumblr.com/4e932aabdfe572f340dbe32cfc06f1cb/840b4b6888f1f93f-e3/s540x810/c3d700cbea3465ba7c8215250e988acb638676e8.png" />
    </div>
</a>
<a asp-action="LogAndReg" asp-controller="User">
    <div style="font: 0px; height: 20px; width: 10px">
        <img style="height: 78px; width: 66px; margin-left: 445px; margin-top: 335px; border-radius: 21px"
            src="https://lh6.googleusercontent.com/proxy/m6StC0KcRIZXbBrdzDRFh3J_H1NeHDRi5RRW_mGn5GnSDd_uxZzpEJoaG9dDz74Lm1CjDbzb7Q-ENv6MqfZlfp5wbTJTDjbp1CxS" />
    </div>
</a>
<a asp-action="LoadingPage" asp-controller="Computer">
    <div style="font: 0px; height: 20px; width: 10px">
        <img style="height: 88px; width: 79px; margin-left: 779px; margin-top: 310px; border-radius: 21px"
            src="https://images.freeimages.com/fic/images/icons/1008/quiet/256/reboot.png?fmt=webp&w=500" />
    </div>
</a>
<a asp-action="DesktopPage">
    <div style="font: 0px; height: 20px; width: 10px">
        <img style="height: 60px; width: 130px; margin-left: 815px; margin-top: 495px; border-radius: 21px"
            src="https://www.clker.com/cliparts/8/Z/N/I/K/K/cancel-button-hi.png" />
    </div>
</a>

Views/Project/Photo.cshtml
@{
    ViewData["Title"] = "photo";
    Layout = "_Empty";
}

<style>
    body {
        background-image: url('https://i.redd.it/evolution-of-picture-folder-thumbnails-v0-hk1gcsxyv5y91.png?width=792&format=png&auto=webp&s=b613b2f7510f1eaaa252e79a3c470aab14cc0770');
        background-size: 100% 100%;
        background-repeat: no-repeat;
        background-position: center;
    }

    .cover {
        position: absolute;
        top: 135px;
        left: 20px;
        width: 97%;
        height: 507px;
        background-color: rgba(252, 252, 252, 255);
        display: flex;
        flex-wrap: wrap;
        justify-content: space-evenly;
    }

    .button {
        margin-top: 4.5%;
        margin-left: 83%;
    }

</style>
<a asp-action="DesktopPage">
    <div>
        <img style="font: 100px; height: 24px; width: 57px; margin-left: 99.5%; margin-top: 13px; border-radius: 0px"
            src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWZALotUkFOOV13iv-KnhMhC2Amsr49Ruh6yRKEYGoDXOpOibGNdvx0VuKiz68K_W9sUA&usqp=CAU" />
    </div>
</a>
<a asp-controller="XP" asp-action="AddPhoto">
    <button class="button">+</button>
</a>

<div class="cover">
    @model List<Photo>
    @foreach (var p in Model)
    {
        <div>
            <img src="@p.ImgURL">
            <p>@p.Title</p>
        </div>

    <form asp-route-photoId="@p.PhotoId" asp-action="DeletePhoto" asp-controller="XP" method="Post">
    <button>
    <img src="https://www.eightforums.com/attachments/recycle_bin_empty-png.40964/" alt="Delete"
    style="width: 20px; height: 20px;">
    </button>
    </form>
    }

</div>

Views/Project/ShuttingDown.cshtml
@{
    ViewData["Title"] = "Shutting Down";
    Layout = "_Empty";
}

<style>
    body {
        background-image: url('https://pronto-core-cdn.prontomarketing.com/2/wp-content/uploads/sites/2276/2014/02/windows_xp_shutdown.jpg');
        background-size: 100% 100%;
        background-repeat: no-repeat;
        background-position: center;
    }
    .click {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 1;
    }
</style>

<audio id="backgroundAudio" autoplay onended>
    <source src="/audio/preview_4.mp3" type="audio/mpeg">
</audio>

<a asp-action="Ups" class="click"></a>

Views/Project/Ups.cshtml
@{
    ViewData["Title"] = "computer";
    Layout = "_Empty";
}


<style>
    body {
        background-image: url('https://gembird.com/Repository/4780/UPS-PC-652A_web_site_image_3B418069-9FE5-4C7A-A167-4275D41F3F2C.jpg');
        background-size: cover;
        background-position: center;
    }
    .button {
        position: absolute;
        top: 500px;
        left: 201px;
        width: 27px;
        height: 22px;
    }
</style>
<a asp-action="LoadingPage">
    <img src="https://pngimg.com/d/dot_PNG35.png" class="button" />
</a>